#  CI/CD Implementation

pipelines:
  branches:
    master:
        - step:
            name: Deploy to Supply Cloud Production
            deployment: production-supply
            clone:
              enabled: false
            script:
              - ssh -A -tt -i /opt/atlassian/pipelines/agent/ssh/id_rsa -o 'StrictHostKeyChecking=no' -p ${PORT:-22} $USER@$SUPPLY_SERVER "bash -c '/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG} ${BITBUCKET_COMMIT}'"
